[package]
name = "logseq_perplexity_integration"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
